DROP TABLE units CASCADE;
DROP TABLE faculty CASCADE;
DROP TABLE offering CASCADE;
DROP TABLE unit_offering CASCADE;

CREATE TYPE study_level_enum AS ENUM ('undergraduate', 'postgraduate', 'research');

CREATE TABLE "units" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "code" varchar NOT NULL,
  "faculty_id" integer,
  "study_level" study_level_enum NOT NULL,
  "sca_band" varchar NOT NULL,
  "eftsl" decimal(5,3) NOT NULL,
  "credit_points" integer NOT NULL,
  "open_to_exchange" boolean NOT NULL,
  "prerequisite" jsonb,
  "corequisite" jsonb,
  "prohibition" jsonb,
  "assessments" jsonb NOT NULL
);

CREATE TABLE "faculty" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL
);

CREATE TABLE "offering" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "location" varchar,
  "teaching_period" varchar,
  "attendance_mode" varchar
);

CREATE TABLE "unit_offering" (
  "unit_id" integer NOT NULL,
  "offering_id" integer NOT NULL,
  PRIMARY KEY ("unit_id", "offering_id")
);

CREATE UNIQUE INDEX "idx_units_code_study_level" ON "units" ("code", "study_level");

CREATE UNIQUE INDEX "idx_offering_unique" ON "offering" ("location", "teaching_period", "attendance_mode");

-- GIN indexes for JSONB columns
CREATE INDEX "idx_units_prerequisite" ON "units" USING GIN ("prerequisite");

CREATE INDEX "idx_units_corequisite"  ON "units" USING GIN ("corequisite");

CREATE INDEX "idx_units_prohibition"  ON "units" USING GIN ("prohibition");

ALTER TABLE "units" ADD FOREIGN KEY ("faculty_id") REFERENCES "faculty" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "unit_offering" ADD FOREIGN KEY ("unit_id") REFERENCES "units" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "unit_offering" ADD FOREIGN KEY ("offering_id") REFERENCES "offering" ("id") DEFERRABLE INITIALLY IMMEDIATE;
